[bbc_loona]
title = "네이버 포스트 ─ Block Berry Creative ─ LOONA"
url = "https://post.naver.com/my/series/detail.nhn?seriesNo=369070&memberNo=39258591"
entrySelector = "#el_list_container ul ul li"
titleSelector = "div.spot_post_name span.ell"
linkSelector = "a[href]"
imageSelector = "img"
contentSelector = "span.writer_name"